---
title: "FinalProject"
author: "Kishan Thambu"
date: "4/18/2022"
output: html_document
---

```{r setup, include=FALSE}
# Installed/Required Packages 
# Geosphere (Required for calculating store distance)
# https://cran.r-project.org/web/packages/geosphere/vignettes/geosphere.pdf
library ("geosphere")
library("ggplot2")

# Data setup
healthfooddata <- read.csv("healthfooddata.csv")
saltlakecitydata <- healthfooddata[which(healthfooddata$city == 'Salt Lake City'),]
provodata <- healthfooddata[which(healthfooddata$city == 'Provo'),]
southjordandata <- healthfooddata[which(healthfooddata$city == 'South Jordan'),]
oremdata <- healthfooddata[which(healthfooddata$city == 'Orem'),]
logandata <- healthfooddata[which(healthfooddata$city == 'Logan'),]
wellingtondata <- healthfooddata[which(healthfooddata$city == 'Wellington'),]
morgandata <- healthfooddata[which(healthfooddata$city == 'Morgan'),]
farmingtondata <- healthfooddata[which(healthfooddata$city == 'Farmington'),]
rooseveltdata <- healthfooddata[which(healthfooddata$city == 'Roosevelt'),]
woodscrossdata <- healthfooddata[which(healthfooddata$city == 'Woods Cross'),]
```

## Summary Statistics on Population

```{r}
summary(saltlakecitydata)
summary(provodata)
summary(southjordandata)
summary(oremdata)
summary(logandata)
summary(wellingtondata)
summary(morgandata)
summary(farmingtondata)
summary(rooseveltdata)
summary(woodscrossdata)
```


Plotting City population and Median Household income


```{r}

# population plot
barplot(c(saltlakecitydata$population[1], provodata$population[1], southjordandata$population[1], oremdata$population[1], logandata$population[1], wellingtondata$population[1], morgandata$population[1], farmingtondata$population[1], rooseveltdata$population[1], woodscrossdata$population[1]), names.arg = c("SLC", "Provo", "South Jordan", "Orem", "Logan", "Wellington", "Morgan", "Farmington", "Roosevelt", "Woods Cross"), xlab = "Cities",
ylab = "Number Of People", main = "Population Bar Plot", col=c("#1b98e0", "#1b98e0", "#1b98e0", "#1b98e0", "#1b98e0",  "#111111", "#111111", "#111111", "#111111", "#111111"), las = 3)

legend("topright",                                    # Add legend to barplot
       legend = c("Urban Cities", "Rural Cities"),
       fill = c("#1b98e0", "#111111"))



# median income plot
barplot(c(saltlakecitydata$median.household.income[1], provodata$median.household.income[1], southjordandata$median.household.income[1], oremdata$median.household.income[1], logandata$median.household.income[1], wellingtondata$median.household.income[1], morgandata$median.household.income[1], farmingtondata$median.household.income[1], rooseveltdata$median.household.income[1], woodscrossdata$median.household.income[1]), names.arg = c("SLC", "Provo", "South Jordan", "Orem", "Logan", "Wellington", "Morgan", "Farmington", "Roosevelt", "Woods Cross"), xlab = "Cities",
ylab = "Median Income by Dollar", main = "Medium Income Bar Plot", col=c("#1b98e0", "#1b98e0", "#1b98e0", "#1b98e0", "#1b98e0",  "#111111", "#111111", "#111111", "#111111", "#111111"), las = 3)

legend("topright",                                    # Add legend to barplot
       legend = c("Urban Cities", "Rural Cities"),
       fill = c("#1b98e0", "#111111"))

# Vehicles (by county)

```


## Store Accessibility

Store Distance

```{r}
# Calculating salt lake city average store distance from longitude and latitude
slcavgdist = 0
for (x in 1:5) {
  i = x + 1
  if (i == 6)
    next
  for (y in i:5) {
    if (x != y) {
      temp = distHaversine(c(saltlakecitydata$longitude[x], saltlakecitydata$latitude[x]),
                           c(saltlakecitydata$longitude[y], saltlakecitydata$latitude[y]))
      slcavgdist = temp + slcavgdist
    }
  }
}
slcavgdist = slcavgdist / 10
```


```{r}
# Calculating logan average store distance from longitude and latitude
loganavgdist = 0
for (x in 1:5) {
  i = x + 1
  if (i == 6)
    next
  for (y in i:5) {
    if (x != y) {
      temp = distHaversine(c(logandata$longitude[x], logandata$latitude[x]),
                           c(logandata$longitude[y], logandata$latitude[y]))
      loganavgdist = temp + loganavgdist
    }
  }
}
loganavgdist = loganavgdist / 10
```

```{r}
# Calculating provo average store distance from longitude and latitude
provoavgdist = 0
for (x in 1:5) {
  i = x + 1
  if (i == 6)
    next
  for (y in i:5) {
    if (x != y) {
      temp = distHaversine(c(provodata$longitude[x], provodata$latitude[x]),
                           c(provodata$longitude[y], provodata$latitude[y]))
      provoavgdist = temp + provoavgdist
    }
  }
}
provoavgdist = provoavgdist / 10
```


```{r}
# Calculating orem average store distance from longitude and latitude
oremavgdist = 0
for (x in 1:5) {
  i = x + 1
  if (i == 6)
    next
  for (y in i:5) {
    if (x != y) {
      temp = distHaversine(c(oremdata$longitude[x], oremdata$latitude[x]),
                           c(oremdata$longitude[y], oremdata$latitude[y]))
      oremavgdist = temp + oremavgdist
    }
  }
}
oremavgdist = oremavgdist / 10
```

```{r}
# Calculating farmington average store distance from longitude and latitude
farmingtonavgdist = 0
for (x in 1:5) {
  i = x + 1
  if (i == 6)
    next
  for (y in i:5) {
    if (x != y) {
      temp = distHaversine(c(farmingtondata$longitude[x], farmingtondata$latitude[x]),
                           c(farmingtondata$longitude[y], farmingtondata$latitude[y]))
      farmingtonavgdist = temp + farmingtonavgdist
    }
  }
}
farmingtonavgdist = farmingtonavgdist / 10
```

```{r}
# Calculating morgan average store distance from longitude and latitude
morganavgdist = 0
for (x in 1:5) {
  i = x + 1
  if (i == 6)
    next
  for (y in i:5) {
    if (x != y) {
      temp = distHaversine(c(morgandata$longitude[x], morgandata$latitude[x]),
                           c(morgandata$longitude[y], morgandata$latitude[y]))
      morganavgdist = temp + morganavgdist
    }
  }
}
morganavgdist = morganavgdist / 10
```

```{r}
# Calculating roosevelt average store distance from longitude and latitude
rooseveltavgdist = 0
for (x in 1:5) {
  i = x + 1
  if (i == 6)
    next
  for (y in i:5) {
    if (x != y) {
      temp = distHaversine(c(rooseveltdata$longitude[x], rooseveltdata$latitude[x]),
                           c(rooseveltdata$longitude[y], rooseveltdata$latitude[y]))
      rooseveltavgdist = temp + rooseveltavgdist
    }
  }
}
rooseveltavgdist = rooseveltavgdist / 10
```

```{r}
# Calculating southjordan average store distance from longitude and latitude
southjordanavgdist = 0
for (x in 1:5) {
  i = x + 1
  if (i == 6)
    next
  for (y in i:5) {
    if (x != y) {
      temp = distHaversine(c(southjordandata$longitude[x], southjordandata$latitude[x]),
                           c(southjordandata$longitude[y], southjordandata$latitude[y]))
      southjordanavgdist = temp + southjordanavgdist
    }
  }
}
southjordanavgdist = southjordanavgdist / 10
```

```{r}
# Calculating wellington average store distance from longitude and latitude
wellingtonavgdist = 0
for (x in 1:5) {
  i = x + 1
  if (i == 6)
    next
  for (y in i:5) {
    if (x != y) {
      temp = distHaversine(c(wellingtondata$longitude[x], wellingtondata$latitude[x]),
                           c(wellingtondata$longitude[y], wellingtondata$latitude[y]))
      wellingtonavgdist = temp + wellingtonavgdist
    }
  }
}
wellingtonavgdist = wellingtonavgdist / 10
```

```{r}
# Calculating woodscross average store distance from longitude and latitude
woodscrossavgdist = 0
for (x in 1:5) {
  i = x + 1
  if (i == 6)
    next
  for (y in i:5) {
    if (x != y) {
      temp = distHaversine(c(woodscrossdata$longitude[x], woodscrossdata$latitude[x]),
                           c(woodscrossdata$longitude[y], woodscrossdata$latitude[y]))
      woodscrossavgdist = temp + woodscrossavgdist
    }
  }
}
woodscrossavgdist = woodscrossavgdist / 10
```

```{r}
# distance plot
barplot(c(slcavgdist, provoavgdist, southjordanavgdist, oremavgdist, loganavgdist, wellingtonavgdist, morganavgdist, farmingtonavgdist, rooseveltavgdist, woodscrossavgdist), names.arg = c("SLC", "Provo", "South Jordan", "Orem", "Logan", "Wellington", "Morgan", "Farmington", "Roosevelt", "Woods Cross"), xlab = "Cities",
ylab = "Distance in Meters (m)", main = "Average Distance between 5 stores", col=c("#1b98e0", "#1b98e0", "#1b98e0", "#1b98e0", "#1b98e0",  "#111111", "#111111", "#111111", "#111111", "#111111"), las = 3)

legend("topright",                                    # Add legend to barplot
       legend = c("Urban Cities", "Rural Cities"),
       fill = c("#1b98e0", "#111111"))

# Vehicles (by county)

```


```{r}
# slc store types
saltlakecityOrganicStoreType<-(saltlakecitydata[which(saltlakecitydata$store.type == 'Organic Grocery Store'),6])
saltlakecityGrocStoreType<-(saltlakecitydata[which(saltlakecitydata$store.type == 'Grocery Store'),6])
saltlakecityConStoreType<-(saltlakecitydata[which(saltlakecitydata$store.type == 'Convenience Store'),6])
saltlakecityTotalStoreTypes=c(length(saltlakecityOrganicStoreType), length(saltlakecityGrocStoreType), length(saltlakecityConStoreType))

# provo store types
provoOrganicStoreType<-(provodata[which(provodata$store.type == 'Organic Grocery Store'),6])
provoGrocStoreType<-(provodata[which(provodata$store.type == 'Grocery Store'),6])
provoConStoreType<-(provodata[which(provodata$store.type == 'Convenience Store'),6])
provoTotalStoreTypes=c(length(provoOrganicStoreType), length(provoGrocStoreType), length(provoConStoreType))

# southjordan store types
southjordanOrganicStoreType<-(southjordandata[which(southjordandata$store.type == 'Organic Grocery Store'),6])
southjordanGrocStoreType<-(southjordandata[which(southjordandata$store.type == 'Grocery Store'),6])
southjordanConStoreType<-(southjordandata[which(southjordandata$store.type == 'Convenience Store'),6])
southjordanTotalStoreTypes=c(length(southjordanOrganicStoreType), length(southjordanGrocStoreType), length(southjordanConStoreType))

# orem store types
oremOrganicStoreType<-(oremdata[which(oremdata$store.type == 'Organic Grocery Store'),6])
oremGrocStoreType<-(oremdata[which(oremdata$store.type == 'Grocery Store'),6])
oremConStoreType<-(oremdata[which(oremdata$store.type == 'Convenience Store'),6])
oremTotalStoreTypes=c(length(oremOrganicStoreType), length(oremGrocStoreType), length(oremConStoreType))

# logan store types
loganOrganicStoreType<-(logandata[which(logandata$store.type == 'Organic Grocery Store'),6])
loganGrocStoreType<-(logandata[which(logandata$store.type == 'Grocery Store'),6])
loganConStoreType<-(logandata[which(logandata$store.type == 'Convenience Store'),6])
loganTotalStoreTypes=c(length(loganOrganicStoreType), length(loganGrocStoreType), length(loganConStoreType))

# wellington store types
wellingtonOrganicStoreType<-(wellingtondata[which(wellingtondata$store.type == 'Organic Grocery Store'),6])
wellingtonGrocStoreType<-(wellingtondata[which(wellingtondata$store.type == 'Grocery Store'),6])
wellingtonConStoreType<-(wellingtondata[which(wellingtondata$store.type == 'Convenience Store'),6])
wellingtonTotalStoreTypes=c(length(wellingtonOrganicStoreType), length(wellingtonGrocStoreType), length(wellingtonConStoreType))

# morgan store types
morganOrganicStoreType<-(morgandata[which(morgandata$store.type == 'Organic Grocery Store'),6])
morganGrocStoreType<-(morgandata[which(morgandata$store.type == 'Grocery Store'),6])
morganConStoreType<-(morgandata[which(morgandata$store.type == 'Convenience Store'),6])
morganTotalStoreTypes=c(length(morganOrganicStoreType), length(morganGrocStoreType), length(morganConStoreType))

# farmington store types
farmingtonOrganicStoreType<-(farmingtondata[which(farmingtondata$store.type == 'Organic Grocery Store'),6])
farmingtonGrocStoreType<-(farmingtondata[which(farmingtondata$store.type == 'Grocery Store'),6])
farmingtonConStoreType<-(farmingtondata[which(farmingtondata$store.type == 'Convenience Store'),6])
farmingtonTotalStoreTypes=c(length(farmingtonOrganicStoreType), length(farmingtonGrocStoreType), length(farmingtonConStoreType))

# roosevelt store types
rooseveltOrganicStoreType<-(rooseveltdata[which(rooseveltdata$store.type == 'Organic Grocery Store'),6])
rooseveltGrocStoreType<-(rooseveltdata[which(rooseveltdata$store.type == 'Grocery Store'),6])
rooseveltConStoreType<-(rooseveltdata[which(rooseveltdata$store.type == 'Convenience Store'),6])
rooseveltTotalStoreTypes=c(length(rooseveltOrganicStoreType), length(rooseveltGrocStoreType), length(rooseveltConStoreType))

# woodscross store types
woodscrossOrganicStoreType<-(woodscrossdata[which(woodscrossdata$store.type == 'Organic Grocery Store'),6])
woodscrossGrocStoreType<-(woodscrossdata[which(woodscrossdata$store.type == 'Grocery Store'),6])
woodscrossConStoreType<-(woodscrossdata[which(woodscrossdata$store.type == 'Convenience Store'),6])
woodscrossTotalStoreTypes=c(length(woodscrossOrganicStoreType), length(woodscrossGrocStoreType), length(woodscrossConStoreType))


# combine two vectors using cbind 
# function
totalStoreTypes=cbind(saltlakecityTotalStoreTypes,provoTotalStoreTypes, southjordanTotalStoreTypes, oremTotalStoreTypes, loganTotalStoreTypes, wellingtonTotalStoreTypes, morganTotalStoreTypes, farmingtonTotalStoreTypes, rooseveltTotalStoreTypes, woodscrossTotalStoreTypes)
  

barplot(totalStoreTypes,beside=T, names.arg = c("SLC", "Provo", "South Jordan", "Orem", "Logan", "Wellington", "Morgan", "Farmington", "Roosevelt", "Woods Cross"), xlab = "Cities",
ylab = "Stores", main = "Store Types found in each city", col=c("#1b98e0", "#111111", "#aaaaaa"), las = 3)

legend("topright",                                    # Add legend to barplot
       legend = c("Organic Grocery Store", "Grocery Store", "Convenience Store"),
       fill = c("#1b98e0", "#111111", "#aaaaaa"))



```

## Confidence Interval on Distance between stores
